export default {
  words: [
    'vnengine',
    'vns',
    'chara',
    'bgm',
    'bgs',
    'blit',
    'GameLoop',
    'EventBus',
    'Preloader',
    'tseslint',
    'eslintConfigPrettier',
    'defineConfig',
    'ignorePaths',
    'verbatimModuleSyntax',
    'erasableSyntaxOnly',
    'noUnusedLocals',
    'noUnusedParameters',
    'noFallthroughCasesInSwitch',
    'allowArbitraryExtensions',
    'moduleDetection',
    'bundler',
    'allowImportingTsExtensions',
    'skipLibCheck',
    'noEmit',
    'vitest',
    'vite',
    'husky',
    'lintstaged',
    'devDependencies',
    'prettierrc',
    'tsconfig',
    'cspell',
  ],
  ignorePaths: [
    'node_modules',
    'dist',
    '.git',
    '.husky',
    'package-lock.json',
    'docs',
  ],
  language: 'en',
};
